[package]
name = "azure"
version = "0.1.0"
edition.workspace = true

[dependencies]
context-switch-core = { workspace = true }

azure-speech = { workspace = true, features = [
	# Use the operating system's trust store for Azure TLS connections.
	"tws-native-tls",
	# Generate WebSocket client handshake keys.
	"tws-rand",
	# Validate the WebSocket server handshake response.
	"tws-smol-sha1",
] }
tokio-native-tls = "0.3.1"

tracing = { workspace = true }
anyhow = { workspace = true }
derive_more = { workspace = true }
futures = { workspace = true }
async-trait = { workspace = true }
async-stream = { workspace = true }
serde = { workspace = true }
url = { workspace = true }
tokio = { workspace = true }

hound = { workspace = true }